name: managing bash profile
on: [push]
       
jobs:
  basic-file-listing:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repo
      uses: actions/checkout@latest
    - name: run local script
      run: sudo ./bash.sh
    - name: set fish as default shell
      run: chsh -s 'which fish'
