name: managing bash profile
on: [push]
       
jobs:
  basic-file-listing:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repo
      uses: actions/checkout@v2
    - name: run local script
      run: ls -lath | bash -x ./bash.sh
    - name: set fish as default shell
      run: chsh -s 'which fish'
