name: managing bash profile
on: [push]
       
jobs:
  basic-file-listing:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repo
      uses: actions/checkout@v2
    - name: list files
      run: ls -lath
    - name: perms
      run:  sudo chmod 755 bash.sh
    - name: list files again
      run: ls -lath
    - name: run local script
      run: bash -x ./bash.sh
    - name: set fish as default shell
      run: chsh -s 'which fish'
