name: managing bash profile
on: [push]
       
jobs:
  basic-file-listing:
    runs-on: ubuntu-latest
    steps: 
    - name: show etc file listing
      run: sudo ls -lath /etc/
    - name: show etc profile
      run: cat /etc/profile
    - name: show bash profile (if exists)
      run: cat ~/.bashrc
    - name: change user
      run: echo "$USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    - name: set fish as default shell
      run: chsh -s 'which fish'
